### ISSUE TITLE
Update to new API

### ISSUE THREAD

**Issue by ufeindt** [singer-io/tap-klaviyo#65]
v1 / v2 legacy APIs are scheduled to be end-of-lifed on Jan 1, 2024 as per [their documentation](https://developers.klaviyo.com/en/v1-2/reference/api-overview).

Here's a [comparison chart](https://developers.klaviyo.com/en/docs/apis_comparison_chart) for the new API. I have only just started looking at this tap, so I don't really know what it would take to update it.

**Comment by maryanngong** [comment]
Hello! Just wanted to check in on this issue -- it looks like v1/v2 legacy APIs will stop working on June 30, 2024 this year. Does anyone know if this migration is currently being worked on? Thanks!!

**Comment by NewAlexandria** [comment]
I wonder how many Stitch / Talend users are relying on this tap, which will fail when the v1 API stops.

**Comment by rawcreative** [comment]
@NewAlexandria we definitely are, our data stopped syncing Apr 20. I've personally sent two emails to Stitch's support regarding the issue and haven't received a single response.

**Comment by maryanngong** [comment]
> @NewAlexandria we definitely are, our data stopped syncing Apr 20. I've personally sent two emails to Stitch's support regarding the issue and haven't received a single response.

I reached out to Stitch's support ~2 weeks ago (because we also use Stitch), and their support team said that they would be doing the upgrade. Specifically they said:
```
Thank you for your patience.
The Stitch R&D team is aware of the upcoming deprecation of the v1 Klaviyo APIs and they are planning to update the integration to use a newer version.
There is not an ETA on when this change will be implemented, but it will be completed before the deprecation.
Please let me know if there are any other questions or concerns.
```

So hopefully that means it should be resolved soon. I am planning to wait another ~2-3 weeks and then reach out again if there is still no upgrade live

**Comment by rdeshmukh15** [comment]
This is the upgrade : https://github.com/singer-io/tap-klaviyo/pull/67
And, these changes have been merged to Master.
